version: '2'
services:
  my-node-app:
    build: ./my-node-app
    ports:
      - "3000:3000"
    links:
      - nodeapi
    depends_on:
      - nodeapi
    environment:
      - API_URL=http://ec2-52-18-216-199.eu-west-1.compute.amazonaws.com:3001
  my-node-api:
    build: ./my-node-api
    ports:
      - "3001:3001"
    links:
      - nodedb
    depends_on:
      - nodedb
    environment:
      - DB_URL=mongodb://db/Poker
  my-mongo-data:
    build: ./my-node-data
  my-node-db:
    build: ./my-node-db
    ports:
      - "27017:27017"
    volumes_from:
      - nodedata
