version: '2'
services:
  nodeapp:
    build: ./my-node-app
    ports:
      - "3000:3000"
    links:
      - nodeApi
    depends_on:
      - nodeApi
    environment:
      - API_URL=http://ec2-52-18-216-199.eu-west-1.compute.amazonaws.com:3001
  nodeapi:
    build: ./my-node-api
    ports:
      - "3001:3001"
    links:
      - nodeDb
    depends_on:
      - nodeDb
    environment:
      - DB_URL=mongodb://db/Poker
  nodedata:
    build: ./my-mongo-data
  nodedb:
    build: ./my-mongo-db
    ports:
      - "27017:27017"
    volumes_from:
      - nodeData
